---
call: DeleteBucketAnalyticsConfiguration 
service: S3
tests:
  - expected:
    op: eq
    path: content
  - expected: dev.cargotel.paws 
    op: eq
    path: parameters
    key: Bucket
  - expected: test1333
    op: eq
    path: parameters
    key: id
  - expected: DELETE 
    op: eq
    path: method
  - expected: https://s3.fake_region.amazonaws.com/dev.cargotel.paws?id=test1333&analytics=
    op: eq
    path: url
  - expected: /oneoffpaws?id=test1333&analytics=
    op: eq
    path: uri
