---
call: DeleteBucketMetricsConfiguration
service: S3
tests:
  - expected: ''
    op: eq
    path: content
  - expected: DELETE
    op: eq
    path: method
  - expected: 1B2M2Y8AsgTpgAmY7PhCfg==
    key: content-md5
    op: eq
    path: headers
  - expected: s3.fake_region.amazonaws.com
    key: host
    op: eq
    path: headers
  - expected: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    key: x-amz-content-sha256
    op: eq
    path: headers
  - expected: oneoffpaws
    key: Bucket
    op: eq
    path: parameters
  - expected: ImportantBlueDocuments
    key: Id
    op: eq
    path: parameters
  - expected: https://s3.fake_region.amazonaws.com/oneoffpaws
    op: eq
    path: url
  - expected: /oneoffpaws
    op: eq
    path: url
  - expected: /oneoffpaws
    op: eq
    path: uri
  - expected: metrics=
    op: eq
    path: uri
  - expected: id=ImportantBlueDocuments
    op: eq
    path: uri

