---
call: GetBucketInventoryConfiguration 
service: S3
tests:
  - expected: oneoffpaws 
    op: eq
    path: parameters
    key: Bucket
  - expected: ImportantBlueDocuments
    op: eq
    path: parameters
    key: Id
  - expected: GET 
    op: eq
    path: method
  - expected: https://s3.fake_region.amazonaws.com/oneoffpaws?
    path: url
  - expected: lifecycle
    path: url
  - expected: Id=ImportantBlueDocuments
    path: url       
  - expected: lifecycle=
    path: uri
  - expected: Id=ImportantBlueDocuments
    path: uri
  - expected: /oneoffpaws?
    path: uri
