---
call: ListBucketAnalyticsConfigurations 
service: S3
tests:
  - expected: 
    op: eq
    path: content
  - expected: oneoffpaws 
    op: eq
    path: parameters
    key: Bucket
  - expected: GET 
    op: eq
    path: method
  - expected: https://s3.fake_region.amazonaws.com/oneoffpaws?continuation-token=&analytics=
    op: eq
    path: url
  - expected: /oneoffpaws?continuation-token=&analytics=
    op: eq
    path: uri
